### ISSUE TITLE
Output is empty

### ISSUE THREAD

**Issue by NyakoFox** [FinnRG/remark-mentions#2]
I'm doing the following:

```
    const output = await unified()
        .use(remarkParse)
        .use(remarkRehype)
        .use(remarkGfm)
        .use(remarkMentions, {
            usernameLink: (username) => `/profile/${username}`,
        })
        .use(rehypeSanitize)
        .use(rehypeStringify)
        .process(input)

    return String(output)
````

However, when I use the output, where the mention once was is empty. Could this be an incompatibility with something? I've tried disabling GFM and rehypeSanitize but the issue persists.

**Comment by FinnRG** [comment]
`remark-mentions` is a markdown plugin. `remark-rehype` turns markdown into html. So you just need to move  `.use(remarkRehype)` below the `remarkMentions` line.

**Comment by NyakoFox** [comment]
Thank you!
